services:
  xbot:
    build: .
    container_name: xbot
    restart: unless-stopped
    ports:
      - "9090:9090" # 管理后台端口
    volumes:
      - ./:/app

volumes:
  redis_data:
    name: redis_data
  xbot:
    name: xbot
