version: "3"

services:
  wechat:
    image: nanssye/xbot-wechat
    container_name: xbot-wechat
    restart: always
    ports:
      - "9011:9011"
      - "9088:9088"

  admin:
    image: nanssye/xbot
    container_name: xbot
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - xbot:/app

networks:
  xbot-network:
    driver: bridge

volumes:
  xbot:
    name: xbot
